const REPLACEMENTS: Array<[RegExp, string]> = [
  [/Invalid LLM response: missing choices\[0\]/g, "LLM 응답이 올바르지 않습니다: choices[0]가 없습니다"],
  [/Invalid LLM response: missing message content/g, "LLM 응답이 올바르지 않습니다: message content가 없습니다"],
  [/Invalid LLM response: unsupported content shape/g, "LLM 응답이 올바르지 않습니다: 지원되지 않는 content 형식입니다"],
  [/Invalid LLM response: fetch returned no response/g, "LLM 응답이 올바르지 않습니다: fetch 응답이 없습니다"],
  [/LLM client requires LOCAL_LLM_API_BASE/g, "LLM 클라이언트에 LOCAL_LLM_API_BASE가 필요합니다"],
  [/LLM client requires LOCAL_LLM_MODEL_NAME/g, "LLM 클라이언트에 LOCAL_LLM_MODEL_NAME가 필요합니다"],
  [/LLM client requires fetch support/g, "LLM 클라이언트에 fetch 지원이 필요합니다"],
  [/LLM request timed out after (\d+)ms/g, "LLM 요청 시간이 $1ms 후 초과되었습니다"],
  [/Invalid numeric env value: ([^\)\n]+)/g, "잘못된 숫자 환경 변수 값: $1"],
  [/Invalid policy file: ([^\n]+?) \((.+?)\)/g, "잘못된 정책 파일: $1 ($2)"],
  [/Session state schema validation failed \(unexpected error\)/g, "세션 상태 스키마 검증에 실패했습니다(예상치 못한 오류)"],
  [/Session state schema validation failed/g, "세션 상태 스키마 검증에 실패했습니다"],
  [/Invalid State: current_task_id \[(.+?)\] is already marked as completed\./g, "잘못된 상태: current_task_id [$1]가 이미 완료된 작업으로 표시되어 있습니다."],
  [/Invalid State: shared_context must be a non-empty object \(Two-Tier structure requirement\)\./g, "잘못된 상태: shared_context는 비어 있지 않은 객체여야 합니다(Two-Tier 구조 요구사항)."],
  [/Invalid State: Task \[(.+?)\] is completed but has no result in task_results\./g, "잘못된 상태: 작업 [$1]은 완료되었지만 task_results에 결과가 없습니다."],
  [/Invalid State: State is not serializable or contains circular references\./g, "잘못된 상태: 상태를 직렬화할 수 없거나 순환 참조가 있습니다."],
  [/Failed to create state directories/g, "상태 디렉터리를 생성하지 못했습니다"],
  [/Failed to save session \[(.+?)\]/g, "세션 [$1] 저장에 실패했습니다"],
  [/Session file \[(.+?)\] is corrupted/g, "세션 파일 [$1]이 손상되었습니다"],
  [/Session file not found \[(.+?)\]/g, "세션 파일 [$1]를 찾지 못했습니다"],
  [/Permission denied reading session \[(.+?)\]/g, "세션 [$1]을(를) 읽을 권한이 없습니다"],
  [/Failed to load session \[(.+?)\]/g, "세션 [$1] 불러오기에 실패했습니다"],
  [/Session already exists \[(.+?)\]/g, "세션 [$1]가 이미 존재합니다"],
  [/Failed to list sessions/g, "세션 목록을 불러오지 못했습니다"],
  [/Checkpoint validation failed/g, "체크포인트 검증에 실패했습니다"],
  [/Failed to create checkpoint \[(.+?)\]/g, "체크포인트 [$1] 생성에 실패했습니다"],
  [/Checkpoint \[(.+?)\] data is invalid/g, "체크포인트 [$1] 데이터가 올바르지 않습니다"],
  [/Checkpoint file not found \[(.+?)\]/g, "체크포인트 파일 [$1]를 찾지 못했습니다"],
  [/Failed to load checkpoint \[(.+?)\]/g, "체크포인트 [$1] 불러오기에 실패했습니다"],
  [/Failed to list checkpoints for session \[(.+?)\]/g, "세션 [$1]의 체크포인트 목록을 불러오지 못했습니다"],
  [/Failed to delete session \[(.+?)\]/g, "세션 [$1] 삭제에 실패했습니다"],
  [/Failed to get latest checkpoint for \[(.+?)\]/g, "[$1]의 최신 체크포인트를 가져오지 못했습니다"],
  [/Failed to build context for task \[(.+?)\]/g, "작업 [$1]의 컨텍스트를 구성하지 못했습니다"],
  [/Failed to normalize execution result for task \[(.+?)\]/g, "작업 [$1]의 실행 결과를 정규화하지 못했습니다"],
  [/Invalid input for ContextSelector\.select/g, "ContextSelector.select에 잘못된 입력이 전달되었습니다"],
  [/Strict Mode Violation: Cannot execute task \[(.+?)\] because its dependencies \[(.+?)\] have failed\./g, "Strict Mode 위반: 작업 [$1]을 실행할 수 없습니다. 의존 작업 [$2]이 실패했습니다."],
  [/Failed to select context for task \[(.+?)\]/g, "작업 [$1]의 컨텍스트 선택에 실패했습니다"],
  [/Dependency result missing for task \[(.+?)\]: depends_on \[(.+?)\] not found in results\./g, "작업 [$1]의 의존성 결과가 없습니다: depends_on [$2]를 결과에서 찾지 못했습니다."],
  [/Task "(.+?)" depends on "(.+?)" which does not exist/g, "작업 \"$1\"은(는) 존재하지 않는 \"$2\"에 의존합니다"],
  [/Cycle detected: (.+)/g, "순환 의존성이 감지되었습니다: $1"],
  [/Task "(.+?)" has no dependencies and no dependents — isolated from the graph/g, "작업 \"$1\"은(는) 의존성도 의존 대상도 없어 그래프에서 고립되었습니다"],
  [/UNKNOWN_DEPENDENCY/g, "알 수 없는 의존성"],
  [/CYCLE_DETECTED/g, "순환 의존성 감지"],
  [/DISCONNECTED_NODE/g, "고립 노드"],
];

export const translateVisibleText = (text: string): string =>
  REPLACEMENTS.reduce((translated, [pattern, replacement]) => translated.replace(pattern, replacement), text);

